apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.17
        args:
        - "server"
        - "-dev"
        - "-dev-listen-address=0.0.0.0:8200"
        ports:
        - containerPort: 8200
          name: http
        securityContext:
          allowPrivilegeEscalation: false
