apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mcp-gateway-ingress.fullname" . }}-httproute
  namespace: {{ tpl (.Values.mcpGateway.namespace) $ }}
spec:
  hostnames:
    - {{ tpl (.Values.mcpGateway.host) $ }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ tpl (.Values.gateway.name) $ }}
      namespace: {{ .Release.Namespace }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ tpl (.Values.mcpGateway.brokerService.name) $ }}
          port: {{ tpl (.Values.mcpGateway.brokerService.port | toString) $ }}
          weight: 1
      filters:
        - responseHeaderModifier:
            add:
              - name: Access-Control-Allow-Origin
                value: '*'
              - name: Access-Control-Allow-Methods
                value: 'GET, POST, PUT, DELETE, OPTIONS, HEAD'
              - name: Access-Control-Allow-Headers
                value: 'Content-Type, Authorization, Accept, Origin, X-Requested-With'
              - name: Access-Control-Max-Age
                value: '3600'
              - name: Access-Control-Allow-Credentials
                value: 'true'
          type: ResponseHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /mcp
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ tpl (.Values.mcpGateway.brokerService.name) $ }}
          port: {{ tpl (.Values.mcpGateway.brokerService.port | toString) $ }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /.well-known/oauth-protected-resource
