apiVersion: v1
kind: Secret
metadata:
  name: oidc-server-credentials
  namespace: mcp-test
  labels:
    mcp.kagenti.com/credential: "true"  # required label for credential secrets
type: Opaque
stringData:
  admin_token: "APIKEY test-api-key-secret-token-for-oidc-server"
