apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      group: sailoperator.io
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
          argocd.argoproj.io/sync-wave: "5"

resources:
  - ../../../operator/base
  - ../../../instance/base
