apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-broker-router
  namespace: mcp-system
  labels:
    app: mcp-broker-router
    component: broker-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-broker-router
      component: broker-router
  template:
    metadata:
      labels:
        app: mcp-broker-router
        component: broker-router
    spec:
      serviceAccountName: mcp-broker-router
      volumes:
        - name: config-volume
          configMap:
            name: mcp-gateway-config
        - name: mcp-credentials # credentials for the broker to user to access MCP backends
          secret:
            secretName: mcp-aggregated-credentials
            defaultMode: 0400
            optional: true # broker can still work without credentials
      containers:
        - name: mcp-broker-router
          image: ghcr.io/kagenti/mcp-gateway:latest
          imagePullPolicy: IfNotPresent
          command:
            - ./mcp_gateway
            - --mcp-gateway-config=/config/config.yaml
            - --mcp-broker-public-address=0.0.0.0:8080
            - --mcp-broker-config-address=0.0.0.0:8181
            - --mcp-router-address=0.0.0.0:50051
            - --log-level=-4 # info level
          env:
            - name: CONFIG_UPDATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mcp-config-update-token
                  key: token
          envFrom:
            - secretRef:
                name: mcp-aggregated-credentials
                optional: true # broker can still work without credentials
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: mcp-credentials
              mountPath: /etc/mcp-credentials
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: config
              containerPort: 8181
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
