---
apiVersion: mcp.kagenti.com/v1alpha1
kind: MCPServer
metadata:
  name: test-server1
  namespace: mcp-test
  labels:
    "kagenti/mcp": "true"
spec:
  # Tool prefix applied to all servers in this MCPServer
  toolPrefix: test_
  targetRef:
    # Server 1 - Go SDK based (hi, time, slow, headers tools)
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mcp-server1-route
---
apiVersion: mcp.kagenti.com/v1alpha1
kind: MCPServer
metadata:
  name: test-server2
  namespace: mcp-test
  labels:
    "kagenti/mcp": "true"
spec:
  toolPrefix: test2_
  targetRef:
    # Server 2 - Go SDK based (hello_world, time, headers, auth1234, slow tools)
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mcp-server2-route
---
apiVersion: mcp.kagenti.com/v1alpha1
kind: MCPServer
metadata:
  name: test-server3
  namespace: mcp-test
  labels:
    "kagenti/mcp": "true"
spec:
  toolPrefix: test3_
  targetRef:
    # Server 3 - Python FastMCP based (time, add, dozen, pi, get_weather, slow)
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mcp-server3-route
---
apiVersion: mcp.kagenti.com/v1alpha1
kind: MCPServer
metadata:
  name: api-key-server
  namespace: mcp-test
  labels:
    "kagenti/mcp": "true"
spec:
  toolPrefix: apikey_
  targetRef:
    # API key test server - validates Bearer token authentication
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mcp-api-key-server-route
  credentialRef:
    name: api-key-server-credentials
    key: token
---
apiVersion: mcp.kagenti.com/v1alpha1
kind: MCPServer
metadata:
  name: custom-path-server
  namespace: mcp-test
  labels:
    "kagenti/mcp": "true"
spec:
  # custom path - this server uses /v1/special/mcp instead of /mcp
  path: /v1/special/mcp
  toolPrefix: custompath_
  targetRef:
    # custom path server - tests non-standard mcp endpoint paths
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mcp-custom-path-server
---
apiVersion: mcp.kagenti.com/v1alpha1
kind: MCPServer
metadata:
  name: oidc-server
  namespace: mcp-test
  labels:
    "kagenti/mcp": "true"
spec:
  # Validates OpenID Connect (OIDC) Bearer tokens issued by a configured OIDC provider
  toolPrefix: oidc_
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mcp-oidc-server-route
  credentialRef:
    name: oidc-server-credentials
    key: admin_token
