apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-gateway
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: mcp-system
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - jsonPointers:
        - /data/config.yaml
        - /metadata/labels
      kind: ConfigMap
      name: mcp-gateway-config
      namespace: mcp-system
    - jsonPointers:
        - /data/token
      kind: Secret
      name: mcp-gateway-config-update-token
      namespace: mcp-system
  project: default
  source:
    chart: mcp-gateway
    repoURL: ghcr.io/kagenti/charts
    targetRevision: 0.3.0
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
